apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-example-api-external-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: "IP_HERE.nip.io"
      http:
        paths:
          - path: /express-example
            pathType: Prefix
            backend:
              service:
                name: express-example-api
                port:
                  number: 80
