apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-example-api-external-ingress
spec:
  defaultBackend:
    service:
      name: express-example-api
      port:
        number: 8080
---
