apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-example-api-external-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "34.162.69.243.nip.io"
    - http:
        paths:
          - path: /express-example
            pathType: Prefix
            backend:
              service:
                name: express-example-api
                port:
                  number: 8081
